# Common Docker compose configuration file for DASH

lb:
  build: ./lb
  ports:
    - "80:80"
    - "443:443"
  links:
    - frontend
    - backend
  #environment:
  #  - DEFAULT_HOST=lumen.akvotest.org
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/certs:/etc/nginx/certs
  restart: always

frontend:
  build: ./frontend
  environment:
    - VIRTUAL_HOST=lumen.akvotest.org

backend:
  build: ./backend
  expose:
    - "3000"
  environment:
    - PORT=3000
    - DATABASE_URL=${LUMEN_DB_URL}
    - FILE_UPLOAD_PATH=${LUMEN_FILE_UPLOAD_PATH}
    - FLOW_REPORT_DATABASE_URL=${LUMEN_FLOW_REPORT_DATABASE_URL}
  restart: always
