# Common Docker compose configuration file for DASH

# Common Docker compose configuration file for DASH

version: '2'
services:
  lb:
    build: ./lb
    ports:
     - "80:80"
     - "443:443"
    links:
     - frontend
     - backend
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - /etc/nginx/certs:/etc/nginx/certs
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - LUMEN_KEYCLOAK_URL
    environment:
     - VIRTUAL_HOST=lumen.akvotest.org

  backend:
    build: ./backend
    expose:
     - "3000"
    environment:
     - PORT=3000
     - LUMEN_DB_URL
     - LUMEN_KEYCLOAK_URL
     - LUMEN_FILE_UPLOAD_PATH
     - LUMEN_FLOW_REPORT_DATABASE_URL
    restart: always
