# -*- mode: ruby -*-
# vi: set ft=ruby :

$whoami = `whoami`.strip
$hosthost = `hostname`.strip
$hostname = $whoami + '.' + $hosthost + '.akvo.devbox'

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.hostname = $hostname
    config.vm.synced_folder "../../../bootstrap/", "/vagrant/bootstrap/"
    config.ssh.forward_agent = true

    config.vm.provision :shell do |s|
        s.path = "../../../bootstrap/bootstrap_vagrant.sh"
    end
end

