# -*- mode: ruby -*-
# vi: set ft=ruby :

$whoami = `whoami`.strip
$hosthost = `hostname`.strip
$hostname = $whoami + '.' + $hosthost + '.akvo.devbox'

Vagrant::Config.run do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.host_name = $hostname
    config.ssh.forward_agent = true

    config.vm.provision :puppet do |puppet|
        puppet.facter = {
            "akvo_vagrant" => "1"
        }
        puppet.module_path = "../../../puppet/modules"
        puppet.manifests_path = "../../../puppet/manifests/"
        puppet.manifest_file = "site.pp"
    end
end


  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "192.168.33.10"

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
