# Configuration file for a development environment
#
# TODO we'll be able to provide "arguments" once docker-compose 1.6.0 is released
# e.g.
#  arguments:
#    - env=whatever
#    - v=X.Y.Z

editor:
  environment:
    - VIRTUAL_HOST=cdb.akvotest.org,*.cdb.akvotest.org
    - RAILS_ENV=development
    - V=3.10.2
    - SUBDOMAIN=akvotest
    - PASSWORD=akvotest
    - ADMIN_PASSWORD=akvotest
    - EMAIL=devops@akvo.org
