# Common Docker Compose configuration file for CartoDB

lb:
  build: ./lb
  ports:
    - "80:80"
    - "443:443"
  links:
    - sqlapi
    - mapsapi
    - editor
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/certs:/etc/nginx/certs
  restart: always

editor:
  build: ./editor
  expose:
    - "3000"
  links:
    - mapsapi
    - sqlapi
  restart: always

sqlapi:
  build: ./sqlapi
  expose:
    - "8080"
  restart: always

mapsapi:
  build: ./mapsapi
  expose:
    - "8181"
  restart: always
