# Configuration file for an hybrid testing environment
# postgres and redis are running on a local vagrant box, both available at 192.168.50.101
#
# TODO we'll be able to provide "arguments" once docker-compose 1.6.0 is released
# e.g.
#  arguments:
#    - env=whatever
#    - v=X.Y.Z

editor:
  environment:
    - VIRTUAL_HOST=cdb.akvotest.org
    - RAILS_ENV=test
    - SUBDOMAIN=akvotest
    - PASSWORD=akvotest
    - ADMIN_PASSWORD=akvotest
    - EMAIL=devops@akvo.org
  extra_hosts:
    - redis:172.31.32.43
    - postgres:172.31.32.43

sqlapi:
  extra_hosts:
    - redis:172.31.32.43
    - postgres:172.31.32.43

mapsapi:
  extra_hosts:
    - redis:172.31.32.43
    - postgres:172.31.32.43
