# Configuration file for a full dockerized development environment
#
# TODO we'll be able to provide "arguments" once docker-compose 1.6.0 is released
# e.g.
#  arguments:
#    - env=whatever
#    - v=X.Y.Z

lb:
  environment:
    - DEFAULT_HOST=cdb.akvotest.org

editor:
  environment:
    - VIRTUAL_HOST=cdb.akvotest.org
    - SUBDOMAIN=akvotest
    - PASSWORD=akvotest
    - ADMIN_PASSWORD=akvotest
    - EMAIL=devops@akvo.org
  extra_hosts:
    - cdb.akvotest.org:192.168.99.100
  links:
    - redis
    - postgres

sqlapi:
  links:
    - redis
    - postgres

mapsapi:
  links:
    - redis
    - postgres

# no need to expose port 5432 - done in base image
postgres:
  build: ./postgres
  volumes:
    - /var/lib/postgresql
  restart: always

# no need to expose port 6379 - done in base image
redis:
  image: redis:3-alpine
  command: redis-server --appendonly yes
  volumes:
    - /data
  restart: always
