# Common Docker Compose configuration file for CartoDB

lb:
  build: ./lb
  ports:
    - "80:80"
    - "443:443"
  links:
    - sqlapi
    - mapsapi
    - editor
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always

editor:
  build: ./editor
  expose:
    - "3000"
  links:
    - redis
    - postgres
    - mapsapi
    - sqlapi
  restart: always

sqlapi:
  build: ./sqlapi
  expose:
    - "8080"
  links:
    - redis
    - postgres
  restart: always

mapsapi:
  build: ./mapsapi
  expose:
    - "8181"
  links:
    - redis
    - postgres
  restart: always

# no need to expose port 5432 - done in base image
postgres:
  build: ./postgres
  volumes:
    - /var/lib/postgresql
  restart: always

# no need to expose port 6379 - done in base image
redis:
  image: redis:3
  command: redis-server --appendonly yes
  volumes:
    - /data
  restart: always
