# -*- mode: ruby -*-
# vi: set ft=ruby :

$whoami = `whoami`.strip
$hosthost = `hostname`.strip
$hostname = $whoami + '.' + $hosthost + '.localdev.akvo.org'

Vagrant.configure("2") do |config|
    config.ssh.forward_agent = true

    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.synced_folder "../../../environments/", "/vagrant/bootstrap/"
    config.vm.synced_folder "../../../", "/puppet/checkout"

    config.vm.define :box1 do |box1|
        box1.vm.network :private_network, ip: "192.168.50.101"
        box1.vm.hostname = "box1." + $hostname
        box1.vm.provision :shell do |s|
            s.path = "../../../environments/bootstrap_vagrant.sh"
            s.args = "localdev_puppet"
        end
    end

    config.vm.define :box2 do |box2|
        box2.vm.network :private_network, ip: "192.168.50.102"
        box2.vm.hostname = "box2." + $hostname
        box2.vm.provision :shell do |s|
            s.path = "../../../environments/bootstrap_vagrant.sh"
            s.args = "localdev_puppet"
        end
    end
end

