# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.hostname = "opendata.localdev.akvo.org"
    config.ssh.forward_agent = true

    config.vm.synced_folder "../../../control/", "/vagrant/bootstrap/"
    config.vm.synced_folder "../../../", "/puppet/checkout/"

    config.vm.network :private_network, ip: "192.168.50.101"

    config.vm.provision :shell do |s|
        s.path = "../../../control/bootstrap_vagrant.sh"
        s.args = "/vagrant/files/localdev_opendata.json"
    end

end

